//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWANCOSMETICS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int id { get; set; }
        public string content { get; set; }
        public string title { get; set; }
        public int user_id { get; set; }
        public int image_id { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime modifiled_at { get; set; }
    
        public virtual Image Image { get; set; }
        public virtual User User { get; set; }
    }
}
